#!/usr/bin/env python3
"""Open a bounded queue of corpus proposals for an account-attributed review."""
import argparse
from datetime import datetime
import json
import os
from pathlib import Path
import subprocess

from cadence import ZONE, activity
from proposal_helpers import corpus_case, git


def api(endpoint, method='GET', payload=None):
    args = ['gh', 'api', endpoint, '--method', method]
    if payload is not None:
        args += ['--input', '-']
    result = subprocess.run(args, input=json.dumps(payload) if payload is not None else None,
                            capture_output=True, text=True, check=True)
    return json.loads(result.stdout) if result.stdout.strip() else None


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--force', action='store_true', help='Permit the initial proposal on a rest day')
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[1]
    repository = os.environ.get('GH_REPO', 'katulevskiy/sequence-corpus')
    if repository != 'katulevskiy/sequence-corpus':
        raise ValueError('This proposal job is scoped to katulevskiy/sequence-corpus')
    now = datetime.now(ZONE)
    today = now.date()
    volume = activity(today)['count']
    quota = max(1, volume)
    slot = min(quota - 1, now.hour * quota // 24)
    batch = f'{today}-{slot}'
    if not args.force and activity(today)['count'] == 0:
        print('Planned rest day; no proposal')
        return
    prefix = 'codex/corpus-proposal-'
    branch = prefix + batch
    pulls = api(f'repos/{repository}/pulls?state=open&per_page=100')
    if any(p['head']['ref'] == branch for p in pulls):
        print('This work session already has an open proposal')
        return
    if sum(p['head']['ref'].startswith(prefix) for p in pulls) >= 6:
        print('Six proposals already await review')
        return
    owner = repository.split('/')[0]
    prior = api(f'repos/{repository}/pulls?state=all&head={owner}:{branch}&per_page=100')
    if prior:
        print('This work session already has a completed proposal')
        return
    if git(root, 'status', '--porcelain'):
        raise RuntimeError('A clean checkout is required')
    relative = f'corpus/proposals/{batch}.tsv'
    content = ''.join(corpus_case(f'{today}:proposal:{slot}:{i:02}')[0] for i in range(32))
    remote = git(root, 'ls-remote', '--heads', 'origin', 'refs/heads/' + branch)
    if remote:
        git(root, 'fetch', 'origin', branch)
        git(root, 'switch', '-c', branch, 'FETCH_HEAD')
        if (root / relative).read_text() != content:
            raise RuntimeError('An existing proposal branch has unexpected content')
    else:
        git(root, 'switch', '-c', branch)
        path = root / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
        git(root, 'add', '--', relative)
        git(root, '-c', 'user.name=github-actions[bot]',
            '-c', 'user.email=41898282+github-actions[bot]@users.noreply.github.com',
            '-c', 'commit.gpgsign=false', 'commit', '-m', f'Add corpus proposal for {batch}')
    subprocess.run(['python3', 'tools/check_corpus.py'], cwd=root, check=True)
    git(root, 'push', 'origin', 'HEAD:refs/heads/' + branch)
    body = (f'Add 32 deterministic cross-language regression examples for session {batch}. '
            'The new shard covers bounded integer inputs and is independent of the daily append file.\n\n'
            'Validation: all shared corpus rows passed the Python, Rust, and C++ runners.\n\n'
            'This proposal was generated by the corpus automation and awaits a review of its diff and expected outputs.\n\n'
            f'<!-- sequence-corpus-proposal:{batch} -->')
    result = api(f'repos/{repository}/pulls', 'POST',
                 {'title': f'Add shared corpus examples for {batch}', 'head': branch, 'base': 'main', 'body': body})
    print(result['html_url'])


if __name__ == '__main__':
    main()
